export const playlists = [
  {
    playlistInfo: {
      id: "1-0",
      playlistCoverImage: "./img/cardImage/image1.jpeg",
      title: "Hip-Hop Hits",
      numberOfTracks: 2,
    },
    tracks: [
      {
        id: "1-0-1",
        artistName: "Eminem",
        trackTitle: "Rap God",
        trackCoverImage: "./img/cardImage/trackList/track1.jpeg",
        trackAudioSrc: "./audio/Eminem - Rap God.mp3",
        isHot: true,
      },
      {
        id: "1-0-2",
        artistName: "50 cent",
        trackTitle: "In da Club",
        trackCoverImage: "./img/cardImage/trackList/track2.jpeg",
        trackAudioSrc: "./audio/50cent - In da club.mp3",
        isHot: false,
      },
      {
        id: "1-0-3",
        artistName: "DMX",
        trackTitle: "X Gon' Give It To Ya",
        trackCoverImage: "./img/cardImage/trackList/track3.jpeg",
        trackAudioSrc: "audio/DMX - X Gon' Give It To Ya.mp3",
        isHot: true,
      },
      {
        id: "1-0-4",
        artistName: "Eminem feat 50 Cent, Cashis, Lloyd Banks",
        trackTitle: "You Don't Know",
        trackCoverImage: "./img/cardImage/trackList/track4.jpeg",
        trackAudioSrc: "audio/Eminem - You Don't Know (feat. 50 cent, Lloyd Banks and Cashis).mp3",
        isHot: true,
      },
    ],
  },
  {
    playlistInfo: {
      id: "1-1",
      playlistCoverImage: "./img/cardImage/image2.jpeg",
      title: "Rap Hits 1990s",
      numberOfTracks: 2,
    },
    tracks: [
      {
        id: "1-1-1",
        artistName: "Public Enemy",
        trackTitle: "Fight the Power",
        trackCoverImage: "./img/cardImage/trackList/track5.jpeg",
        trackAudioSrc: "./audio/Public Enemy - Fight The Power.mp3",
        isHot: true,
      },
      {
        id: "1-1-2",
        artistName: "Vanila Ice",
        trackTitle: "Ice Ice Baby",
        trackCoverImage: "./img/cardImage/trackList/track6.jpeg",
        trackAudioSrc: "./audio/Vanila Ice - Ice Baby.mp3",
        isHot: false,
      },
      {
        id: "1-1-3",
        artistName: "MC Hammer",
        trackTitle: "You Can’t Touch This",
        trackCoverImage: "./img/cardImage/trackList/track7.jpeg",
        trackAudioSrc: "audio/Mc Hammer - You Can't Touch This.mp3",
        isHot: true,
      },
      {
        id: "1-1-4",
        artistName: "Brand Nubian",
        trackTitle: "Brand Nubian",
        trackCoverImage: "./img/cardImage/trackList/track8.jpeg",
        trackAudioSrc: "audio/Brand Nubian - Brand Nubian.mp3",
        isHot: true,
      },
    ],
  },
];